INSERT INTO movies (imdbid, tmdbid, title, year, poster_url, backdrop_url, note, genre, runtime_minutes, summary, director, "cast") VALUES
('tt1757678',  '83533',   'Avatar: Fire and Ash',         '2025', 'https://image.tmdb.org/t/p/original/lE9KpVwgeWHMwgwkNaeH5nEFh20.jpg', 'https://image.tmdb.org/t/p/original/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg', 7.4,  ARRAY[878, 12, 14],              197, 'Following a devastating conflict with the RDA and the death of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a fierce and power-hungry Na''vi tribe led by the ruthless Varang. The family must fight for survival and Pandora''s future, tested to their emotional and physical limits.', 'James Cameron',                    ARRAY['Sam Worthington','Zoe Saldaña','Sigourney Weaver','Stephen Lang','Oona Chaplin']),
('tt33071426', '1325734', 'The Drama',                    '2026', 'https://image.tmdb.org/t/p/original/gCbtFTIBdwpOI5KRp8dSrK6hm6x.jpg', 'https://image.tmdb.org/t/p/original/1oKLEA9JOhvaBwLpqjROisvWMy7.jpg', 7.5,  ARRAY[10749, 35, 18],            106, 'A couple preparing for their wedding plays a confession game with friends, during which the bride reveals a shocking secret that threatens to unravel their relationship before the ceremony.',                                                                                                                                     'Kristoffer Borgli',                ARRAY['Zendaya','Robert Pattinson','Alana Haim','Mamoudou Athie']),
('tt12042730', '687163',  'Project Hail Mary',            '2026', 'https://image.tmdb.org/t/p/original/1hJdqwEDES96CRZCaiOVuqWLJFX.jpg', 'https://image.tmdb.org/t/p/original/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg', 8.4 , ARRAY[878, 12],                  156, 'A lone astronaut awakens on a spacecraft millions of kilometers from Earth, the sole survivor of a mission to the Tau Ceti system. Facing mysterious circumstances and the deaths of crew members, he gradually realizes his survival determines not just mission success, but the future of the entire human population.',         'Phil Lord, Christopher Miller',    ARRAY['Ryan Gosling','James Ortiz','Sandra Hüller','Lionel Boyce','Milana Vayntrub']),
('tt28650488', '1226863', 'The Super Mario Galaxy Movie', '2026', 'https://image.tmdb.org/t/p/original/lggrFZlEDu3kmic1DnZl9c6bcD9.jpg', 'https://image.tmdb.org/t/p/original/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg', 6.5,  ARRAY[16, 12, 35, 10751, 14],    98,  'Mario and Luigi, along with Princess Peach and Toad, embark on a new adventure. Guided by mysterious star catapults, they travel through the galaxy, landing on different planets where they encounter new enemies and allies.',                                                                                                    'Aaron Horvath, Michael Jelenic',   ARRAY['Chris Pratt','Charlie Day','Anya Taylor-Joy','Jack Black','Keegan-Michael Key']),
('tt26443616', '1327819', 'Hoppers',                      '2026', 'https://image.tmdb.org/t/p/original/nP3oMYwggLjnv5v1oQSmUso6yTd.jpg', 'https://image.tmdb.org/t/p/original/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg', 7.7,  ARRAY[16, 12, 35, 10751, 878],   105, 'A nature-loving protagonist transforms into a beaver and makes startling discoveries. Instead of following established rules, she disrupts the natural order by initiating an animal uprising with the intention of preserving a pond ecosystem.',                                                                                  'Daniel Chong',                     ARRAY['Piper Curda','Bobby Moynihan','Jon Hamm','Kathy Najimy','Dave Franco']),
('tt30851137', '1159831', 'The Bride!',                   '2026', 'https://image.tmdb.org/t/p/original/9HNcs1Y3bKVKp4BB4TQO5oDe0b2.jpg', 'https://image.tmdb.org/t/p/original/l8rKKMU2M9dDULO9CEtDNdWAEUJ.jpg', 6.1,  ARRAY[878, 27, 14],              127, 'A lonely Frankenstein travels to 1930s Chicago with Dr. Euphronius to create a companion. They resurrect a murdered young woman, giving birth to the Bride. She exceeds their expectations, igniting a passionate romance while attracting police attention and sparking a radical social movement.',                               'Maggie Gyllenhaal',                ARRAY['Jessie Buckley','Christian Bale','Peter Sarsgaard','John Magaro','Jeannie Berlin']),
('tt8036976',  '1198994', 'Send Help',                    '2026', 'https://image.tmdb.org/t/p/original/nKbcjoO2BDkA3r5oR3Z8LnHHNXw.jpg', 'https://image.tmdb.org/t/p/original/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg', 7.2,  ARRAY[27, 53, 35],               114, 'Linda Liddle, an overlooked employee, finds herself stranded on a deserted island following a plane crash alongside her supervisor Bradley Preston. Their struggle for survival becomes a tense power dynamic filled with workplace tensions and mutual distrust.',                                                                 'Sam Raimi',                        ARRAY['Rachel McAdams','Dylan O''Brien','Edyll Ismail','Dennis Haysbert','Xavier Samuel']),
('tt27613895', '1297842', 'GOAT',                         '2026', 'https://image.tmdb.org/t/p/original/gGPGkuq8chdbOdiuf1ipkXiRQL1.jpg', 'https://image.tmdb.org/t/p/original/tq3h43fZy0H80vzf47MAY7R9Mxo.jpg', 6.9,  ARRAY[16, 35, 10751],            100, 'A small goat named Will pursues his dream of joining a professional sports team to play Roarball. Despite initial skepticism from teammates, he remains determined to revolutionize the sport and prove that size doesn''t limit greatness.',                                                                                       'Tyree Dillihay',                   ARRAY['Caleb McLaughlin','Gabrielle Union','Stephen Curry','Aaron Pierre','Nicola Coughlan']),
('tt15239678', '693134',  'Dune: Part Two',               '2024', 'https://image.tmdb.org/t/p/original/rjmLNTt5tP1obYx4YFzLHpN7KcG.jpg', 'https://image.tmdb.org/t/p/original/oBCR7ShGq9ZdnHMK8SGOckGpEgo.jpg', 8.1,  ARRAY[878, 12, 18],              167, 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',                                                                                                                                                                   'Denis Villeneuve',                 ARRAY['Timothée Chalamet','Zendaya','Rebecca Ferguson','Josh Brolin']),
('tt0062622',  '62',      '2001: A Space Odyssey',        '1968', 'https://image.tmdb.org/t/p/original/nqRGmBJb2lsHnfKHzo8zJUxrru0.jpg', 'https://image.tmdb.org/t/p/original/30XRuUQGk5P9XB6mlfEF1eoWFgq.jpg', 8.3,  ARRAY[878, 9648],                149, 'Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000, the world''s most advanced super computer.',                                                                                                                                                        'Stanley Kubrick',                  ARRAY['Keir Dullea','Gary Lockwood','William Sylvester']),
('tt28231777', '1104937', 'Kill the Jockey',              '2025', 'https://image.tmdb.org/t/p/original/hSJBlgVhmqdb4nJdx7F96m9rJRn.jpg', 'https://image.tmdb.org/t/p/original/we01Y32b8YT5Pn7vLIhunbmROhX.jpg', 7.6,  ARRAY[18],                       97,  'Remo''s self-destructive behavior overshadows his talent as a jockey. Abril, pregnant with his baby, must decide between the child or continuing to race.',                                                                                                                                                                         'Luis Ortega',                      ARRAY['Nahuel Pérez Biscayart','Úrsula Corberó'])
ON CONFLICT (imdbid) DO NOTHING;

INSERT INTO featured_movies (imdbid, position) VALUES
('tt1757678',  1),  -- Avatar: Fire and Ash
('tt12042730', 2),  -- Project Hail Mary
('tt15239678', 3),  -- Dune: Part Two
('tt28650488', 4),  -- The Super Mario Galaxy Movie
('tt33071426', 5),  -- The Drama
('tt26443616', 6),  -- Hoppers
('tt30851137', 7),  -- The Bride!
('tt8036976',  8),  -- Send Help
('tt27613895', 9)   -- GOAT
;
